// --- Telegram WebApp Integration ---
if (window.Telegram && window.Telegram.WebApp) {
  try {
    const tg = window.Telegram.WebApp;
    tg.ready();
    tg.expand();
    if (tg.setHeaderColor) tg.setHeaderColor('#266431');
    if (tg.setBackgroundColor) tg.setBackgroundColor('#f6f5ef');
  } catch(e) {}
}
function tgHaptic(type) {
  if (window.Telegram && window.Telegram.WebApp && window.Telegram.WebApp.HapticFeedback) {
    try {
      if (type === 'selection') window.Telegram.WebApp.HapticFeedback.selectionChanged();
      else if (type === 'success' || type === 'error') window.Telegram.WebApp.HapticFeedback.notificationOccurred(type);
      else window.Telegram.WebApp.HapticFeedback.impactOccurred(type);
    } catch(e) {}
  }
}
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>';
const down = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M12 4v16M6 14l6 6 6-6"/></svg>';
const products = {
  formula: {name:'Формула 1',sub:'Збалансований коктейль · Банановий крем',image:'formula.png',desc:'Коли зранку хочеться простіше. Коктейль із білком, клітковиною, вітамінами та мінералами — один із варіантів зручного прийому їжі.',meta:'550 г · Готуй за інструкцією на упаковці. Містить сою; перевір склад та алергени.',url:'https://www.herbalife.com/uk-ua/u/products/formula-1-balanced-cocktail-banana-cream-550g-4462'},
  tea: {name:'Трав’яний концентрат',sub:'Напій із чайними екстрактами · Лимон',image:'tea.png',desc:'Тепла пауза між справами. Чайний напій, який можна пити гарячим або холодним — як тобі подобається.',meta:'51 г · Містить кофеїн. Не замінює воду чи повноцінне харчування. Вживай за інструкцією.',url:'https://www.herbalife.com/uk-ua/u/products/instant-herbal-beverage-with-tea-extracts-lemon-51g-180k'},
  collagen: {name:'Колаген Б’юті Комплекс',sub:'Herbalife SKIN · Полуниця та лимон',image:'collagen.png',desc:'Ще один привід зробити паузу для себе. Напій із колагеном як частина щоденного ритуалу догляду.',meta:'171 г · Харчова добавка. Склад, алергени й спосіб вживання — на упаковці.',url:'https://www.herbalife.com/uk-ua/u/products/collagen-skin-booster-strawberry-lemon-171g-076k'},
  bars: {name:'Протеїнові міні-батончики',sub:'Ваніль у хрусткій карамелі',image:'bars.png',desc:'Перекус, який поміщається в сумку. Для дороги, прогулянки чи паузи між справами.',meta:'28 міні-батончиків · Перевір склад і алергени. Кількість білка залежить від порції.',url:'https://www.herbalife.com/uk-ua/u/products/mini-protein-bars-vanilla-crunchy-caramel-28-bites-001k'}
};
const programs={breakfast:{title:'3 дні. Почнемо зі сніданку.',short:'Тест-драйв · 3 дні',desc:'Знайомство з Анною, ідеї для сніданків і розбір твого звичного ранку. Обери бажаний день першої зустрічі.'},movement:{title:'7 днів у своєму ритмі.',short:'Новий ритм · 7 днів',desc:'Тиждень уваги до харчування, руху й режиму. План щоденних кроків та підтримка Анни — без обіцянок певної кількості кілограмів.'},selfcare:{title:'10 днів турботи про себе.',short:'Ритуал турботи · 10 днів',desc:'Сон, вода, харчування і догляд — збираємо рутину, для якої знайдеться місце у твоєму дні.'},protein:{title:'Знайомство з твоїм раціоном.',short:'Пробний розбір харчування',desc:'Обговоримо твої звичні страви, джерела білка та зручні зміни. Це консультація про харчування, а не лабораторний тест.'},training:{title:'Зустрінемось у русі.',short:'Пробне тренування',desc:'Обери бажану дату й час знайомства з тренуванням. Формат та навантаження обговорюються індивідуально.'}};
const stories=[
 {id:'breakfast',cls:'one',title:'Ранок, який<br>на твоєму боці.',label:'THE BREAKFAST EDIT',offer:'03 ДНІ · ТЕСТ-ДРАЙВ',description:'Пошта почекає. Спочатку — щось смачне для себе. Збираємо сніданок, що вписується у твоє життя.',cta:'Спробувати 3 дні',image:'breakfast.webp',alt:'Ранковий стіл із коктейлем, полуницями, авокадо та вівсянкою',product:'formula',tags:['Сніданок','Нові звички','Твій темп'],spots:[{x:74,y:39,mx:54,my:58,key:'formula',label:'Що в коктейлі?'},{x:51,y:73,mx:7,my:76,key:'breakfast',label:'3 дні разом',type:'program'}]},
 {id:'movement',cls:'two',title:'Менше «треба».<br>Більше руху.',label:'THE EVERYDAY RESET',offer:'07 ДНІВ · НОВИЙ РИТМ',description:'Нормально поїсти. Вийти на прогулянку. Повторити завтра. Тиждень простих дій, з яких починаються зміни.',cta:'Приєднатися на 7 днів',image:'movement.webp',alt:'Зелений салат, вода, яблуко, килимок для йоги та кросівки',product:'tea',tags:['Їжа','Рух','Підтримка'],spots:[{x:70,y:64,mx:42,my:69,key:'bars',label:'Перекус із собою'},{x:83,y:25,mx:65,my:51,key:'training',label:'Пробне тренування',type:'program'}]},
 {id:'selfcare',cls:'three',title:'Турбота —<br>теж план.',label:'THE SLOW GLOW',offer:'10 ДНІВ · ДЛЯ СЕБЕ',description:'Вода біля ліжка. Вечір без поспіху. Їжа, яку ти любиш. Даємо щоденній турботі місце в календарі.',cta:'Обрати 10 днів для себе',image:'selfcare.webp',alt:'Ритуал догляду з рожевим напоєм, грейпфрутом, алое та рушником',product:'collagen',tags:['Ритуали','Догляд','Харчування'],spots:[{x:73,y:37,mx:55,my:59,key:'collagen',label:'Мій beauty-ритуал'},{x:50,y:70,mx:7,my:76,key:'selfcare',label:'Почати з малого',type:'program'}]},
 {id:'protein',cls:'four',title:'А білка<br>вистачає?',label:'THE PROTEIN CHECK',offer:'01 ХВИЛИНА · ДЛЯ ЦІКАВОСТІ',description:'Усі говорять про білок. Почнімо з тебе: прикинемо базовий орієнтир і подивимось, де він є у звичних стравах.',cta:'Перевірити свій орієнтир',image:'breakfast.webp',alt:'Збалансований сніданок із коктейлем та натуральними продуктами',product:'bars',tags:['Білок','Твоя тарілка','Без здогадок'],spots:[{x:78,y:35,mx:70,my:55,key:'formula',label:'Один із варіантів'}]}
];
function hotspot(s){return `<div class="hotspot ${s.type==='program'?'activity':''}" style="--x:${s.x}%;--y:${s.y}%;--mx:${s.mx}%;--my:${s.my}%"><button class="dot" data-${s.type==='program'?'program-peek':'product'}="${s.key}" aria-label="${s.label}" aria-expanded="false">+</button><span class="hotspot-label">${s.label}</span></div>`}
function story(s,i){return `<section class="story story-${s.cls}" id="${s.id}" aria-labelledby="title-${s.id}"><div class="story-panel"><img class="story-picture" src="./assets/${s.image}" alt="${s.alt}" loading="lazy" width="1536" height="1024"><div class="story-head"><span class="chapter">${s.label}</span><span class="story-number">0${i+1} / 04</span></div><div class="story-content"><p class="eyebrow">${s.offer}</p><h2 id="title-${s.id}">${s.title}</h2><p class="story-description">${s.description}</p><button class="pill ${i===0?'lime':'outline'}" ${s.id==='protein'?'data-calculator':'data-book="'+s.id+'"'}>${s.cta}${arrow}</button></div>${s.spots.map(hotspot).join('')}<button class="scene-product" data-product="${s.product}" aria-label="Відкрити ${products[s.product].name}" aria-expanded="false"><img src="./assets/${products[s.product].image}" alt="Herbalife ${products[s.product].name}" loading="lazy"></button>${s.id==='protein'?'<div class="protein-callout"><span>ОРІЄНТИР EFSA · 18+</span><strong>0,83</strong><small>г білка / кг ваги на день<br>для здорових дорослих</small><button class="dot" data-calculator aria-label="Розрахувати білок">+</button></div>':''}<div class="story-bottom"><div class="ingredients">${s.tags.map(t=>'<span>'+t+'</span>').join('')}</div><span class="tiny"><span class="desktop-label">Наведи на +. Тут є дещо для тебе.</span><span class="mobile-label">Торкнись +</span></span></div></div></section>`}
document.querySelector('#app').innerHTML=`
<a class="skip" href="#stories">До інтерактивних історій</a>
<header class="header"><a href="#top" class="brand" aria-label="Анна PRO BALANCE — на початок"><span class="brand-word">anna<span>.</span></span><small>PRO<br>BALANCE</small></a><nav class="nav" aria-label="Головна навігація"><a href="#stories">Твій баланс</a><a href="#about">Знайомимось</a><a href="#protein">А що з білком?</a></nav><button class="pill small" data-book="breakfast">Почати з 3 днів${arrow}</button><button class="menu-toggle" aria-label="Відкрити меню" aria-expanded="false">☰</button></header>
<section class="hero" id="top"><div class="hero-top"><p class="eyebrow section-kicker">ХАРЧУВАННЯ. РУХ. ТИ.</p><span class="edition"><span class="line"></span>ЩОДНЯ / ДЛЯ СЕБЕ</span></div><div class="hero-copy"><h1>Спочатку —<br><em>ти.</em></h1><div class="hero-aside"><p>Кава вже була. А сніданок?<br>Знайдемо місце для нього.<br>І для твоїх нових звичок.</p><button class="pill" data-book="breakfast">Спробувати зі мною${arrow}</button></div></div><div class="hero-gallery"><a class="preview-card" href="#movement"><img src="./assets/movement.webp" alt="Свіжі продукти, вода та рух" width="1536" height="1024"><div class="preview-note"><span>02 / THE EVERYDAY RESET</span>Твій новий ритм.</div></a><div class="preview-card center"><img src="./assets/breakfast.webp" alt="Сонячний сніданок із коктейлем і ягодами" width="1536" height="1024" fetchpriority="high"><span class="image-tag">РАНОК У ТВОЄМУ РИТМІ</span><div class="preview-note"><span>01 / THE BREAKFAST EDIT</span>Спочатку — ти. Потім — плани.</div><div class="gallery-dot"><button class="dot" data-product="formula" aria-label="Дізнатися про коктейль" aria-expanded="false">+</button></div></div><a class="preview-card" href="#selfcare"><img src="./assets/selfcare.webp" alt="Тихий ритуал турботи про себе" width="1536" height="1024"><div class="preview-note"><span>03 / THE SLOW GLOW</span>Турбота — теж план.</div></a></div><div class="hero-sideword">GOOD FOOD.<br>REAL LIFE.<br><span>WITH ANNA.</span></div><div class="hero-foot"><a href="#stories">ГОРТАЙ СВОЮ ІСТОРІЮ ${down}</a><span class="hint"><i>+</i><span class="desktop-label">Наведи. Відкрий. Спробуй.</span><span class="mobile-label">Торкнись. Відкрий. Спробуй.</span></span></div></section>
<section class="intro"><p class="eyebrow">ТВІЙ БАЛАНС НЕ СХОЖИЙ НА ЧУЖИЙ</p><h2>Ранок без поспіху. Смачний обід.<br>Прогулянка просто так.<br><span>Здоров’я живе в таких речах.</span></h2><p>Обери історію, яка зараз про тебе. Решту зберемо разом.</p></section>
<nav class="story-nav" id="stories" aria-label="Обрати історію"><a href="#breakfast" class="active"><span>01</span> Ранок</a><a href="#movement"><span>02</span> Новий ритм</a><a href="#selfcare"><span>03</span> Турбота</a><a href="#protein"><span>04</span> Білок</a></nav>
<div class="stories">${stories.map(story).join('')}</div>
<section class="about" id="about"><div class="portrait-wrap"><div class="portrait"><img src="./assets/anna.webp" alt="Анна з коктейлем за столом" loading="lazy"><span class="portrait-caption">Анна · твоя людина в PRO BALANCE</span></div><div class="signature">Анна ♡</div></div><div class="about-copy"><p class="eyebrow section-kicker">ПРИВІТ, Я АННА</p><h2>У плані харчування<br>має бути місце<br>для життя.</h2><p>Для сніданків нашвидкуруч. Для вечерь із друзями. Для днів, коли сил вистачає тільки на щось просте.</p><p>Я допоможу розібратися у звичках, зібрати зручний раціон і знайти свій темп. Почнемо з розмови про тебе — що любиш, як живеш і що хочеш змінити.</p><button class="pill" data-book="protein">Познайомимось?${arrow}</button><div class="about-meta"><span>Харчування без крайнощів</span><span>Крок за кроком</span></div></div></section>
<section class="closing"><p class="eyebrow">НЕ ОБОВ’ЯЗКОВО ЧЕКАТИ ПОНЕДІЛКА</p><h2>Три ранки.<br>Одна нова звичка.</h2><p>Три дні знайомства. Твій звичний ритм. Трохи більше уваги до себе.</p><button class="pill lime" data-book="breakfast">Почати з 3 днів${arrow}</button></section>
<footer class="footer"><div class="footer-top"><a href="#top" class="brand"><span class="brand-word">anna.</span><small>PRO<br>BALANCE</small></a><p>Їжа. Рух. Турбота. У твоєму ритмі.</p><a href="#top" class="back-top">Нагору ↑</a></div><div class="footer-bottom"><p>Особистий простір Анни. У добірках представлено продукцію Herbalife. Це не офіційний сайт бренду. Продукти — частина різноманітного харчування; індивідуальні результати відрізняються.</p><span>© 2026 PRO BALANCE<br>З увагою до тебе.</span></div></footer>
<aside class="product-popover" id="product-popover" aria-label="Коротка картка" hidden></aside>
<dialog class="dialog" id="booking-dialog" aria-labelledby="booking-title"></dialog>
<dialog class="dialog" id="protein-dialog" aria-labelledby="protein-title"></dialog>`;

const popover=document.querySelector('#product-popover');
const bookingDialog=document.querySelector('#booking-dialog');
const proteinDialog=document.querySelector('#protein-dialog');
let activeTrigger=null, hideTimer=null;
const canHover=matchMedia('(hover:hover) and (pointer:fine)');
function closePopover(){popover.hidden=true;activeTrigger?.setAttribute('aria-expanded','false');activeTrigger=null;clearTimeout(hideTimer)}
function positionPopover(trigger){if(innerWidth<=700)return;const rect=trigger.getBoundingClientRect();const width=330;const height=popover.offsetHeight;let left=rect.left-width-16;if(left<16)left=rect.right+16;left=Math.max(16,Math.min(left,innerWidth-width-16));let top=Math.max(16,Math.min(rect.top-80,innerHeight-height-16));popover.style.left=left+'px';popover.style.top=top+'px'}
function openPopover(trigger){tgHaptic('selection');clearTimeout(hideTimer);activeTrigger?.setAttribute('aria-expanded','false');activeTrigger=trigger;trigger.setAttribute('aria-expanded','true');const key=trigger.dataset.product;const p=products[key];const program=programs[trigger.dataset.programPeek];if(p){popover.innerHTML=`<button class="pop-close" aria-label="Закрити картку">×</button><p class="pop-eyebrow">У МОЄМУ РИТУАЛІ · HERBALIFE</p><div class="pop-body"><img class="pop-image" src="./assets/${p.image}" alt="${p.name}"><div><h3 class="pop-title">${p.name}</h3><p class="pop-sub">${p.sub}</p></div></div><p class="pop-desc">${p.desc}</p><p class="pop-meta">${p.meta}</p><a class="pop-link" href="${p.url}" target="_blank" rel="noopener noreferrer">Склад на сайті виробника ↗</a><button class="pill pop-button" data-order="${key}">Хочу спробувати · замовити${arrow}</button>`}else if(program){popover.innerHTML=`<button class="pop-close" aria-label="Закрити картку">×</button><p class="pop-eyebrow">ЧАС ДЛЯ СЕБЕ · З АННОЮ</p><h3 class="pop-title">${program.title}</h3><p class="pop-desc">${program.desc}</p><p class="pop-meta">Індивідуальний формат. Деталі та вартість — під час знайомства.</p><button class="pill pop-button" data-book="${trigger.dataset.programPeek}">Обрати дату й час${arrow}</button>`}popover.hidden=false;positionPopover(trigger)}
document.querySelectorAll('[data-product],[data-program-peek]').forEach(trigger=>{trigger.addEventListener('pointerenter',()=>{if(canHover.matches)openPopover(trigger)});trigger.addEventListener('pointerleave',()=>{if(canHover.matches)hideTimer=setTimeout(closePopover,240)});trigger.addEventListener('focus',()=>openPopover(trigger));trigger.addEventListener('click',e=>{e.stopPropagation();if(activeTrigger===trigger&&!popover.hidden&&trigger.dataset.clicked==='true'){closePopover();trigger.dataset.clicked='false'}else{openPopover(trigger);trigger.dataset.clicked='true'}})});
popover.addEventListener('pointerenter',()=>clearTimeout(hideTimer));popover.addEventListener('pointerleave',()=>{if(canHover.matches)hideTimer=setTimeout(closePopover,300)});popover.addEventListener('focusin',()=>clearTimeout(hideTimer));
document.addEventListener('click',e=>{const target=e.target.closest('button,a');if(target?.matches('.pop-close'))closePopover();if(target?.dataset.book)openBooking(target.dataset.book);if(target?.dataset.order)openBooking('order',target.dataset.order);if(target?.hasAttribute('data-calculator'))openProtein();if(!e.target.closest('.product-popover,.hotspot,.gallery-dot,.scene-product'))closePopover()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closePopover()}if(e.key==='Tab'&&activeTrigger&&!popover.hidden){clearTimeout(hideTimer);if(e.target===activeTrigger&&!e.shiftKey){e.preventDefault();popover.querySelector('button,a')?.focus()}}});
document.addEventListener('focusin',e=>{if(activeTrigger&&!popover.contains(e.target)&&e.target!==activeTrigger)closePopover()});
function kyivParts(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date()).reduce((a,p)=>(a[p.type]=p.value,a),{})}
function today(){const p=kyivParts();return `${p.year}-${p.month}-${p.day}`}
function showDialog(dialog){closePopover();dialog.showModal();document.body.classList.add('no-scroll')}
function closeDialog(dialog){dialog.close();document.body.classList.remove('no-scroll')}
function wireDialog(dialog){dialog.addEventListener('click',e=>{if(e.target===dialog||e.target.closest('[data-close]'))closeDialog(dialog)});dialog.addEventListener('close',()=>document.body.classList.remove('no-scroll'))}
wireDialog(bookingDialog);wireDialog(proteinDialog);
function openBooking(key,productKey){if(proteinDialog.open)closeDialog(proteinDialog);const isOrder=key==='order';const config=isOrder?{title:'Спробуємо?',short:'Замовлення · '+products[productKey].name,desc:'Обери бажану дату й час розмови про продукт. Наявність, вартість і спосіб отримання узгоджуються окремо.'}:programs[key]||programs.breakfast;bookingDialog.innerHTML=`<div class="dialog-inner"><button class="dialog-close" data-close aria-label="Закрити форму">×</button><p class="eyebrow">PRO BALANCE · ${isOrder?'ТВОЯ ДОБІРКА':'ЗУСТРІЧ ІЗ АННОЮ'}</p><h2 id="booking-title">${config.title}</h2><p class="dialog-intro">${config.desc}</p><form id="booking-form"><label class="field">${isOrder?'Продукт':'Формат'}<input name="program" value="${config.short}" readonly></label><label class="field">Як до тебе звертатися?<input name="name" placeholder="Твоє ім’я" maxlength="60" autocomplete="given-name" required></label><div class="fields-row"><label class="field">Бажана дата<input type="date" name="date" min="${today()}" required></label><label class="field">Час за Києвом<select name="time" required><option value="">Обрати час</option>${['09:00','10:30','12:00','14:00','15:30','17:00','18:30'].map(t=>`<option>${t}</option>`).join('')}</select></label></div><p class="demo-note">Це приклад форми. Дані нікуди не надсилаються; реальна зустріч або замовлення не створюється.</p><p class="form-error" role="alert"></p><button class="pill submit" type="submit">${isOrder?'Підтвердити вибір':'Обрати цей час'}${arrow}</button></form></div>`;const form=bookingDialog.querySelector('form');form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const name=data.get('name').trim();const date=data.get('date');const time=data.get('time');const now=kyivParts();if(!name){form.querySelector('.form-error').textContent='Вкажи, будь ласка, ім’я.';return}if(date<today()||(date===today()&&time<=`${now.hour}:${now.minute}`)){form.querySelector('.form-error').textContent='Цей час уже минув. Обери майбутню дату або час.';return}const dateText=new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long',year:'numeric'}).format(new Date(date+'T12:00:00'));if (window.Telegram && window.Telegram.WebApp) {
  try {
    window.Telegram.WebApp.HapticFeedback?.notificationOccurred('success');
    window.Telegram.WebApp.sendData(JSON.stringify({
      event: 'booking_consultation',
      program: config.short,
      name: name,
      date: dateText,
      time: time
    }));
  } catch(e) {}
}
bookingDialog.querySelector('.dialog-inner').innerHTML=`<button class="dialog-close" data-close aria-label="Закрити">×</button><div class="success"><div class="success-icon">✓</div><p class="eyebrow">ПРИКЛАД ПІДТВЕРДЖЕННЯ</p><h2 id="booking-title">Ось так це працює.</h2><p id="success-name"></p><div class="summary"><strong>${config.short}</strong><br>${dateText} · ${time} за Києвом</div><p class="demo-note">Це демонстрація. Заявку не надіслано, оплату не здійснено, час не заброньовано.</p><button class="pill submit" data-close>Повернутися до історій${arrow}</button></div>`;bookingDialog.querySelector('#success-name').textContent=`${name}, твій вибір зібрано. У робочій версії тут буде наступний крок знайомства з Анною.`;bookingDialog.querySelector('[data-close]').focus()});showDialog(bookingDialog)}
function openProtein(){proteinDialog.innerHTML=`<div class="dialog-inner"><button class="dialog-close" data-close aria-label="Закрити калькулятор">×</button><p class="eyebrow">THE PROTEIN CHECK · 18+</p><h2 id="protein-title">Почнімо з орієнтира.</h2><p class="dialog-intro">Вкажи вагу — отримаєш базовий референтний рівень білка для здорової дорослої людини.</p><label class="field">Твоя вага, кг<input id="weight" type="number" min="35" max="220" value="65" step="1" inputmode="decimal"></label><input class="range" id="weight-range" type="range" min="35" max="220" value="65" aria-label="Обрати вагу в кілограмах"><div class="protein-result" aria-live="polite"><strong id="protein-value">54</strong> <span>г / день</span><p id="protein-math">65 кг × 0,83 г</p></div><p class="source-note">За референтним значенням <a href="https://www.efsa.europa.eu/en/press/news/120209" target="_blank" rel="noopener noreferrer">EFSA: 0,83 г/кг на день</a>. Це популяційний орієнтир, а не індивідуальна норма чи діагностика дефіциту. Спорт, вагітність, грудне вигодовування та стан здоров’я потребують окремої оцінки.</p><div class="protein-meal">Білок уже є у звичних продуктах: яйцях, рибі, бобових, тофу, кисломолочних продуктах. Добавки не обов’язкові.</div><button class="pill submit" data-book="protein">Розібрати моє харчування${arrow}</button></div>`;const weight=proteinDialog.querySelector('#weight');const range=proteinDialog.querySelector('#weight-range');function update(source){let val=Number(source.value);const valid=Number.isFinite(val)&&val>=35&&val<=220;proteinDialog.querySelector('#protein-value').textContent=valid?Math.round(val*.83):'—';proteinDialog.querySelector('#protein-math').textContent=valid?`${val} кг × 0,83 г`:'Вкажи вагу від 35 до 220 кг';if(valid){if(source===range)weight.value=val;else range.value=val}}weight.addEventListener('input',()=>update(weight));range.addEventListener('input',()=>update(range));showDialog(proteinDialog)}
const menu=document.querySelector('.menu-toggle');const nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const expanded=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!expanded));menu.setAttribute('aria-label',expanded?'Відкрити меню':'Закрити меню');nav.classList.toggle('open',!expanded)});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
const storyElements=[...document.querySelectorAll('.story')];const storyLinks=[...document.querySelectorAll('.story-nav a')];const reducedMotion=matchMedia('(prefers-reduced-motion:reduce)');let framePending=false;
function onScroll(){if(framePending)return;framePending=true;requestAnimationFrame(()=>{const headerOffset=innerWidth<=700?120:140;let active=0;storyElements.forEach((section,i)=>{const rect=section.getBoundingClientRect();if(rect.top<=innerHeight*.45)active=i;if(!reducedMotion.matches){const progress=Math.max(0,Math.min(1,(innerHeight-rect.top)/(innerHeight-headerOffset)));const panel=section.querySelector('.story-panel');panel.style.setProperty('--inset',`${(1-progress)*3}%`);panel.style.setProperty('--zoom',String(1.06-progress*.06))}});storyLinks.forEach((a,i)=>{a.classList.toggle('active',i===active);if(i===active)a.setAttribute('aria-current','true');else a.removeAttribute('aria-current')});if(!reducedMotion.matches){const hero=document.querySelector('.hero');hero.style.setProperty('--film-scroll',`${Math.min(scrollY*.2,180)}px`)}if(activeTrigger&&!popover.hidden)closePopover();framePending=false})}
window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',onScroll);onScroll();
